name: geoecology
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - matplotlib=3.8.*
  - seaborn
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rasterio
  - rasterstats
  - folium
  - scikit-learn
  - statsmodels
  - openpyxl
  - xlrd
  - ipympl
